
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=DTX&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1&noclutter=0&showstorms=99&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24759278&lat=0&lon=0&label=you
    name: Radar
    
  - platform: mjpeg
    name: Front Door
    mjpeg_url: http://10.0.1.135:8083/axis-cgi/mjpg/video.cgi?cameraId=257365207
    

  - platform: mjpeg
    mjpeg_url: http://localhost:8991
    name: Printer
    
  - platform: mjpeg
    name: Living Room
    mjpeg_url: http://10.0.1.135:8083/axis-cgi/mjpg/video.cgi?cameraId=1171543357
    
  - platform: mjpeg
    name: Kitchen
    mjpeg_url: http://10.0.1.135:8083/axis-cgi/mjpg/video.cgi?cameraId=1171543357
    
